CREATE TABLE time_deposits
(
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plan_type VARCHAR(255),
    balance   DOUBLE PRECISION,
    days      INT                                  NOT NULL,
    CONSTRAINT pk_time_deposits PRIMARY KEY (id)
);

CREATE TABLE withdrawals
(
    id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    time_deposit_id INT                                  NOT NULL,
    amount          DECIMAL(19, 2)                       NOT NULL,
    date            date                                 NOT NULL,
    CONSTRAINT pk_withdrawals PRIMARY KEY (id)
);

ALTER TABLE withdrawals
    ADD CONSTRAINT FK_WITHDRAWALS_ON_TIME_DEPOSIT FOREIGN KEY (time_deposit_id) REFERENCES time_deposits (id);